// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEiknqxNFqBofzD48PCLkIpIJjJlohtEM',
    appId: '1:462234740929:web:2a2077a1481b5a27724c40',
    messagingSenderId: '462234740929',
    projectId: 'learnli-1ebd7',
    authDomain: 'learnli.in',
    storageBucket: 'learnli-1ebd7.firebasestorage.app',
    measurementId: 'G-QQP37KDYV1',
    databaseURL: 'https://learnli-1ebd7-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr8Ouo3Dyn-tTIvMtNXB7o3WAt9AYIZCk',
    appId: '1:462234740929:android:fe9855730b855af6724c40',
    messagingSenderId: '462234740929',
    projectId: 'learnli-1ebd7',
    storageBucket: 'learnli-1ebd7.firebasestorage.app',
    databaseURL: 'https://learnli-1ebd7-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDag3cwTOtNteySFKkiiOUmhAyOyEylfbU',
    appId: '1:462234740929:ios:d4d4d210ff3a8695724c40',
    messagingSenderId: '462234740929',
    projectId: 'learnli-1ebd7',
    storageBucket: 'learnli-1ebd7.firebasestorage.app',
    databaseURL: 'https://learnli-1ebd7-default-rtdb.firebaseio.com/',
    iosBundleId: 'com.example.studyBuddyFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDag3cwTOtNteySFKkiiOUmhAyOyEylfbU',
    appId: '1:462234740929:ios:697001d17cfb2adb724c40',
    messagingSenderId: '462234740929',
    projectId: 'learnli-1ebd7',
    storageBucket: 'learnli-1ebd7.firebasestorage.app',
    databaseURL: 'https://learnli-1ebd7-default-rtdb.firebaseio.com/',
    iosBundleId: 'com.example.studyBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEiknqxNFqBofzD48PCLkIpIJjJlohtEM',
    appId: '1:462234740929:web:f3faedb6246a8d20724c40',
    messagingSenderId: '462234740929',
    projectId: 'learnli-1ebd7',
    authDomain: 'learnli.in',
    storageBucket: 'learnli-1ebd7.firebasestorage.app',
    measurementId: 'G-STRJEWWFVG',
    databaseURL: 'https://learnli-1ebd7-default-rtdb.firebaseio.com/',
  );
}
